import { createContext, useContext, useState } from 'react'

const translations = {
    en: {
        appTitle: 'EarnGuard', appSub: 'AI-powered income protection for gig workers',
        step1Title: 'Who are you?', step1Desc: 'Tell us about your gig work so we can personalize your protection.',
        step2Title: 'Choose your plan', step2Desc: 'Pick the coverage that fits your income level.',
        step3Title: 'Activate protection', step3Desc: 'Review your plan and start protecting your income.',
        name: 'Full Name', namePh: 'e.g. Rahul Sharma',
        jobType: 'Job Type', selectJob: 'Select your gig type',
        city: 'City', cityPh: 'e.g. Mumbai',
        weekly: 'Weekly', monthly: 'Monthly',
        maxIncome: 'Up to', perWeek: '/week', perMonth: '/month',
        coverage: 'coverage', popular: 'Most Popular',
        customIncome: 'Your weekly income', customPh: 'Enter amount',
        next: 'Continue', back: 'Back', skip: 'Skip',
        activate: 'Activate Protection',
        coveredUp: 'You are covered up to', forPrice: 'for',
        expectedIncome: 'Expected Income', actualIncome: 'Actual Income',
        compensation: 'Compensation', incomeLoss: 'Income Loss',
        riskLevel: 'Risk Level', aiInsight: 'AI Insight',
        youAreProtected: 'You are protected!', compIssued: 'compensation issued.',
        noPayout: 'No payout needed this week. Your earnings are on track!',
        assessAgain: 'Assess Again',
        earningsHistory: 'Earnings History', expected: 'Expected', actual: 'Actual',
        totalProtected: 'Total Protected', weeksProtected: 'Weeks Protected',
        fiveDayForecast: '5-Day Forecast', estComp: 'Est. Compensation',
        totalEstComp: 'TOTAL EST. COMPENSATION',
        weeklyReport: 'Weekly AI Report', highRiskDays: 'High-Risk Days',
        totalComp: 'Total Compensation', mostImpacted: 'Most Impacted',
        weatherMap: 'Weather & Risk Map',
        streakLabel: 'weeks protected', upgrade: 'Upgrade to',
        demoMode: 'DEMO MODE', exitDemo: 'Exit Demo',
        planBadge: 'COVERAGE',
        enterIncome: 'Enter expected weekly income',
        analyzeRisk: 'Analyze Risk',
        upgradeMsg: 'Your plan covers up to',
        upgradeOr: 'or enter',
        instead: 'instead',
        weeklyAssessment: 'Weekly risk assessment',
    },
    hi: {
        appTitle: 'अर्नगार्ड', appSub: 'गिग वर्कर्स के लिए AI-संचालित आय सुरक्षा',
        step1Title: 'आप कौन हैं?', step1Desc: 'अपने गिग कार्य के बारे में बताएं।',
        step2Title: 'अपना प्लान चुनें', step2Desc: 'अपनी आय स्तर के अनुसार कवरेज चुनें।',
        step3Title: 'सुरक्षा सक्रिय करें', step3Desc: 'अपने प्लान की समीक्षा करें और सुरक्षा शुरू करें।',
        name: 'पूरा नाम', namePh: 'उदा. राहुल शर्मा',
        jobType: 'कार्य प्रकार', selectJob: 'अपना गिग प्रकार चुनें',
        city: 'शहर', cityPh: 'उदा. मुंबई',
        weekly: 'साप्ताहिक', monthly: 'मासिक',
        maxIncome: 'अधिकतम', perWeek: '/सप्ताह', perMonth: '/माह',
        coverage: 'कवरेज', popular: 'सबसे लोकप्रिय',
        customIncome: 'आपकी साप्ताहिक आय', customPh: 'राशि दर्ज करें',
        next: 'आगे बढ़ें', back: 'पीछे', skip: 'छोड़ें',
        activate: 'सुरक्षा सक्रिय करें',
        coveredUp: 'आप सुरक्षित हैं', forPrice: 'के लिए',
        expectedIncome: 'अपेक्षित आय', actualIncome: 'वास्तविक आय',
        compensation: 'मुआवजा', incomeLoss: 'आय हानि',
        riskLevel: 'जोखिम स्तर', aiInsight: 'AI अंतर्दृष्टि',
        youAreProtected: 'आप सुरक्षित हैं!', compIssued: 'मुआवजा जारी।',
        noPayout: 'इस सप्ताह भुगतान की आवश्यकता नहीं। आपकी कमाई सही दिशा में है!',
        assessAgain: 'फिर से आकलन करें',
        earningsHistory: 'आय इतिहास', expected: 'अपेक्षित', actual: 'वास्तविक',
        totalProtected: 'कुल संरक्षित', weeksProtected: 'संरक्षित सप्ताह',
        fiveDayForecast: '5-दिन का पूर्वानुमान', estComp: 'अनु. मुआवजा',
        totalEstComp: 'कुल अनुमानित मुआवजा',
        weeklyReport: 'साप्ताहिक AI रिपोर्ट', highRiskDays: 'उच्च-जोखिम दिन',
        totalComp: 'कुल मुआवजा', mostImpacted: 'सबसे प्रभावित',
        weatherMap: 'मौसम और जोखिम मानचित्र',
        streakLabel: 'सप्ताह मजबूत', upgrade: 'अपग्रेड करें',
        demoMode: 'डेमो मोड', exitDemo: 'डेमो बंद करें',
        planBadge: 'कवरेज',
        enterIncome: 'अपेक्षित साप्ताहिक आय दर्ज करें',
        analyzeRisk: 'जोखिम विश्लेषण करें',
        upgradeMsg: 'आपका प्लान अधिकतम कवर करता है',
        upgradeOr: 'या दर्ज करें',
        instead: 'इसके बजाय',
        weeklyAssessment: 'साप्ताहिक जोखिम आकलन',
    },
    te: {
        appTitle: 'ఎర్న్‌గార్డ్', appSub: 'గిగ్ వర్కర్ల కోసం AI-ఆధారిత ఆదాయ రక్షణ',
        step1Title: 'మీరు ఎవరు?', step1Desc: 'మీ గిగ్ పని గురించి చెప్పండి.',
        step2Title: 'మీ ప్లాన్ ఎంచుకోండి', step2Desc: 'మీ ఆదాయ స్థాయికి తగిన కవరేజ్ ఎంచుకోండి.',
        step3Title: 'రక్షణ సక్రియం చేయండి', step3Desc: 'మీ ప్లాన్‌ను సమీక్షించి రక్షణ ప్రారంభించండి.',
        name: 'పూర్తి పేరు', namePh: 'ఉదా. రాహుల్ శర్మ',
        jobType: 'ఉద్యోగ రకం', selectJob: 'మీ గిగ్ రకాన్ని ఎంచుకోండి',
        city: 'నగరం', cityPh: 'ఉదా. ముంబై',
        weekly: 'వారపు', monthly: 'నెలవారీ',
        maxIncome: 'గరిష్టం', perWeek: '/వారం', perMonth: '/నెల',
        coverage: 'కవరేజ్', popular: 'అత్యంత ప్రజాదరణ',
        customIncome: 'మీ వారపు ఆదాయం', customPh: 'మొత్తం నమోదు చేయండి',
        next: 'కొనసాగించు', back: 'వెనుకకు', skip: 'దాటవేయి',
        activate: 'రక్షణ సక్రియం చేయి',
        coveredUp: 'మీరు రక్షించబడ్డారు', forPrice: 'కోసం',
        expectedIncome: 'అంచనా ఆదాయం', actualIncome: 'వాస్తవ ఆదాయం',
        compensation: 'పరిహారం', incomeLoss: 'ఆదాయ నష్టం',
        riskLevel: 'నష్ట స్థాయి', aiInsight: 'AI అంతర్దృష్టి',
        youAreProtected: 'మీరు రక్షించబడ్డారు!', compIssued: 'పరిహారం జారీ.',
        noPayout: 'ఈ వారం చెల్లింపు అవసరం లేదు. మీ ఆదాయం సరిగ్గా ఉంది!',
        assessAgain: 'మళ్ళీ అంచనా వేయండి',
        earningsHistory: 'ఆదాయ చరిత్ర', expected: 'అంచనా', actual: 'వాస్తవ',
        totalProtected: 'మొత్తం రక్షించబడింది', weeksProtected: 'రక్షించబడిన వారాలు',
        fiveDayForecast: '5-రోజుల సూచన', estComp: 'అంచనా పరిహారం',
        totalEstComp: 'మొత్తం అంచనా పరిహారం',
        weeklyReport: 'వారపు AI నివేదిక', highRiskDays: 'అధిక-నష్ట రోజులు',
        totalComp: 'మొత్తం పరిహారం', mostImpacted: 'ఎక్కువ ప్రభావం',
        weatherMap: 'వాతావరణ & నష్ట మ్యాప్',
        streakLabel: 'వారాలు బలంగా', upgrade: 'అప్‌గ్రేడ్ చేయి',
        demoMode: 'డెమో మోడ్', exitDemo: 'డెమో నిష్క్రమించు',
        planBadge: 'కవరేజ్',
        enterIncome: 'అంచనా వారపు ఆదాయం నమోదు చేయండి',
        analyzeRisk: 'నష్ట విశ్లేషణ',
        upgradeMsg: 'మీ ప్లాన్ గరిష్టంగా కవర్ చేస్తుంది',
        upgradeOr: 'లేదా నమోదు చేయి',
        instead: 'బదులుగా',
        weeklyAssessment: 'వారపు నష్ట అంచనా',
    },
}

const LangCtx = createContext()

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('eg_lang') || 'en')
    const changeLang = (l) => { setLang(l); localStorage.setItem('eg_lang', l) }
    const t = (key) => translations[lang]?.[key] || translations.en[key] || key
    return <LangCtx.Provider value={{ lang, setLang: changeLang, t }}>{children}</LangCtx.Provider>
}

export const useLang = () => useContext(LangCtx)
export const LANGUAGES = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'हिंदी' },
    { code: 'te', label: 'తెలుగు' },
]
